### ISSUE TITLE
Hacktoberfest promotion

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#114]
Ticket to cover various devrel work on Hacktoberfest, to include:

- [x] [Create a graphic to use when promoting/requesting contributions](https://github.com/kedro-org/kedro-viz/issues/1549)
- [ ] Create social posts to use on Mastodon (Kedro account) 
- [x] Create suggested copy for LinkedIn for personal posts by the team, using the graphic.
- [x] Create copy for Slack to promote the event, using the graphic
- [ ] Create incentives? Shall we order some stickers for people that contribute with a "I was there, Kedro Hacktoberfest 2023" kind of thing? If so, we can mention these in the copy above. Alternative incentives could be adding them to the #kedroids channel, named in the release notes and call out in our channels
- [x] @astrojuanlu you mentioned some sites that list projects looking for contributions. Can you include links/list them here please?
- [x] Create a section in "In the Pipeline Oct 2023" #113

**Comment by stichbury** [comment]
cc @astrojuanlu

**Comment by stichbury** [comment]
With the stickers, there's no rush to get these as long as we agree we will do them. We can mention them and get them created and sent out for end of month, but we don't need them for the start of the month.

**Comment by stephkaiser** [comment]
I got some fun sticker ideas :)

**Comment by stephkaiser** [comment]
@stichbury depends on budget i guess! i have some stickers mocked up in case we want to get them printed, just let me know :)

**Comment by astrojuanlu** [comment]
I'll ping you about stickers :) 

Sites I found to promote Kedro or at least make sure we appear:

- https://goodfirstissue.dev/
- https://www.codetriage.com/
- https://up-for-grabs.net/
- https://www.firstissue.dev/
- https://hacktoberfest-projects.vercel.app/
- The `#project-sharing` channel of the Hacktoberfest Discord https://discord.gg/hacktoberfest

We could also rework #3130 into a blog post on Dev.to https://dev.to/t/hacktoberfest23

**Comment by stichbury** [comment]
OK, so can we divvy up the rest of the work on this:

**Comment by astrojuanlu** [comment]
The only remaining item left is defining the incentives. Getting their PRs merged in a high-profile project + getting named in the release notes and the Slack announcement (as we usually do with community contributions) could be enough of an incentive. Do we think we need more?

**Comment by stichbury** [comment]
> Do we think we need more?

STICKERS.

**Comment by merelcht** [comment]
Closing as Hacktoberfest 2023 has finished.
