### ISSUE TITLE
Create a blog post about our new video course

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#120]
This could be a short section for In the Pipeline but I'd rather we create the content that we would have had on Udemy so we make the Kedro blog the front page for the course, keyword optimised with useful content, links and review feedb ack.

**Comment by stichbury** [comment]
@astrojuanlu I was thinking about this some more (showerthoughts) and decided that we need more than a blog post about the course, we also need a "front page" for it to send to people for information.

We could do this on the website but we don't have a mock up design or page for it yet (which we could cue up while we work on the content). But I am wondering if it would actually be OK/sensible to make it a page of documentation (so don't make it promotional, make it a factual set of links to the videos or even embeds).

OR

We could make a page on `awesome-kedro` which isn't so high-ranking but would be an option. 

Any thoughts, ideas, beliefs, views and philosophies welcome.

**Comment by stichbury** [comment]
@astrojuanlu there's a brief above for you to use for the blog post. I'm happy to write it but want to offer you first refusal (and feel free to discard the brief if you have prefer your own structure).

**Comment by astrojuanlu** [comment]
I'll give it a go 💪🏽

**Comment by stichbury** [comment]
This is done and published
