### ISSUE TITLE
Different board for blog content

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-devrel#122]
@merelcht suggested that we have issues (not really "issues", but pending tasks) related to blog posts appear in a different board.

To be completed.

**Comment by stichbury** [comment]
So raise them here on `kedro-devrel` as issues but enter them into a different project board to track them?

Or have a different repo?

**Comment by astrojuanlu** [comment]
I created https://github.com/orgs/kedro-org/projects/6/ but only [org owners](https://github.com/orgs/kedro-org/people?query=role%3Aowner) can make it public.

**Comment by astrojuanlu** [comment]
@merelcht 🙏🏽

**Comment by astrojuanlu** [comment]
Done!
