### ISSUE TITLE
Write a blog post about sharing/hosting Viz on GCP/Azure

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-devrel#135]
Write a follow up blog post to https://kedro.org/blog/how-to-share-a-kedro-viz-pipeline-visualisation with the release of this feature on Azure and GCP in Kedro-Viz 8.0.0.

**Comment by rashidakanchwala** [comment]
Closing this as publish and share on other platforms is very similar to AWS and our docs cover the whole thing properly. 

We can reopen this in future if required or if we had some distinguishing newer features on shareable-viz.
