### ISSUE TITLE
Find alternative to Orbit

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-devrel#137]
We were using Orbit (RIP) as a "community CRM" to gather insights about our users, and now it's gone. Some functionalities I was using a lot:

- Enriching profiles with extra information to derive insights
- Keep track of interests
- Keep track of delivered swag
- Keep track of timeline of events (GitHub star, Slack signup, first question, first pull request)
- etc

Some alternatives (from the fantastic folks at DevRel Collective):

- https://www.commonroom.io/ (most recommended one)
- ~~https://www.crowd.dev/~~ (large parts are open source!)
- https://www.reo.dev/

Other ideas:

- Build a custom integration + Hubspot
- Apparently none of Zapier, IFTTT, Make support tracking GitHub stars (arguably the most basic requirement)
- Custom Kedro pipeline? 💀

**Comment by astrojuanlu** [comment]
- https://talkbase.io/ (has a free plan)

**Comment by yetudada** [comment]
I've just [popped a message into the DevRelX by Slashdata community Slack](https://devrelx.slack.com/archives/CJPTMV4CQ/p1713437344568999). I'll revert if they say anything.

**Comment by yetudada** [comment]
Here are the comments from DevRelX: 
 - Common Room is something I have heard that most DevRel teams use.
 - There is also [Crowd.dev](http://crowd.dev/) (OSS and just acquired by Linux Foundation)

I think we should test Crowd.dev, they have a non-profit account that we can use while Vizro goes through the motion of onboarding them. It might also be worth getting a demo of Reo, I'm curious about how they hook up things like npm, Docker etc. 

> Yes, we offer discounts (up to 100%) for non-profits, start ups, and non-commercial open source projects. Send an email to [hello@crowd.dev](mailto:hello@crowd.dev) to get in touch.

**Comment by astrojuanlu** [comment]
That's exciting. I'll shoot them an email ASAP

**Comment by astrojuanlu** [comment]
Sent

**Comment by astrojuanlu** [comment]
Crowd "recently got acquired by The Linux Foundation, therefore [...] don’t take on any new customers"

**Comment by astrojuanlu** [comment]
Upcoming hosted version of crowd.dev https://getsphere.dev/

**Comment by astrojuanlu** [comment]
Reo.dev doesn't have public pricing and TalkBase free plan has only 1 integration, compared with 2 with CommonRoom.

Talkbase however has more affordable pricing options for small teams.

**Comment by astrojuanlu** [comment]
We've been using the free plan of CommonRoom for some time and are satisfied with it for now. Closing.
