### ISSUE TITLE
Write blog post about Kedro+Ibis+BigQuery

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-devrel#138]
Idea from @DimedS using https://docs.kedro.org/projects/kedro-datasets/en/latest/api/kedro_datasets.ibis.TableDataset.html

**Comment by DimedS** [comment]
The first draft is available here: https://github.com/DimedS/kedro-ibis-bigquery.
I received feedback from @stichbury  and will be adding a section: "Why Kedro is helpful for that task".

**Comment by astrojuanlu** [comment]
This looks wonderful! 🙌🏼 

After giving it a very quick read, my only comment is that maybe I'd extract points 1 and 2 from "Implementation Steps" to some sort of intro, and I'd leave steps from 3 onwards (hence the creation of the project).

Then, if you could pass `ruff` to the code snippets for consistency that would be perfect.

And a very minor thing, not a huge fan of `/conf/base/...`, I'd rather write `conf/base` (to avoid signaling that these have to be at the filesystem root)

**Comment by astrojuanlu** [comment]
This is undergoing the final reviews.

**Comment by astrojuanlu** [comment]
Published! Thanks @DimedS ⭐
