### ISSUE TITLE
Record and publish video on `vscode-kedro`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-devrel#139]
https://marketplace.visualstudio.com/items?itemName=kedro.Kedro

@noklam agreed to record the video himself, we need to discuss content and format.

Ideally, it should be a short (<8 minutes) video showcasing all the use cases presented in the README:

- Go to Definition (from pipeline to configuration)
- Find References (from configuration to pipeline)
- Pipeline autocompletion
- Schema validation

**Comment by noklam** [comment]
Let's connect on how to make some progress this sprint. I had WGO and another presentation so I am not optimistic I can finish everything this sprint.

My idea is a similar flow like the Coffee Chat, namely VSCode extension + a few VS Code tricks. I don't know what kind of software I should use for editing yet, any suggestion?

I was thinking recording the screen / audio separately. I like the Key Cast that I used during the presentation, I don't know how easy it is to record with it as it's tricky to make it less noisy (alternative is post edit the shortcut to the video)

**Comment by astrojuanlu** [comment]
No worries, let's push it to the next sprint if need be.

After lots of iteration, I managed to minimise the preparation and post-production effort by just using [OBS](https://obsproject.com/). It's open source, it's widely used, and it's awesome. There's no shortage of videotutorials on how to use it. 

It's geared towards live streaming, which makes it perfect for videos that will rarely be edited afterwards. The only thing you need is to set up the "scenes" that you want and configure the keyboard shortcuts to transition between them. See for example:

https://youtu.be/f_KSUBLO3a4?si=io4FcAF4iwJKfmj9&t=34

When I make a mistake on camera, I just stay quiet for a second and try to say the sentence again. Then I upload the whole thing to YouTube and cut the fragments I don't like.

My recording gear is the iPhone camera mounted on a tripod with light.

> I was thinking recording the screen / audio separately. I like the Key Cast that I used during the presentation, I don't know how easy it is to record with it as it's tricky to make it less noisy (alternative is post edit the shortcut to the video)

Whatever works best for you. For me the key thing was to keep it as simple as possible.

Let's continue the conversation internally.

**Comment by noklam** [comment]
I have a busy sprint and couldn't find time to record a draft. I did manage to do a few rehearsals (it's taking about 6-7 minutes) and setup my OBS. I will continue on this once the related VSCode ticket is ready, since I want to show them in the Video as well.

I do find that it's hard to record it in one-go, so I am thinking to do a screen recording and voice over separately.

**Comment by astrojuanlu** [comment]
https://www.youtube.com/watch?v=hz17QtZCLMM !
