### ISSUE TITLE
Create dashboard to track PyPI downloads

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-devrel#146]
See #145 for extra context.

**Comment by lid-rs** [comment]
First Version of the PyPI downloads available here: https://prod-useast-b.online.tableau.com/#/site/mckinseyusproduction/views/PyPIDownloadsDashboard/Dashboard1?:iid=1
Layout and design refinement in progress

**Comment by astrojuanlu** [comment]
We will be making incremental improvements 🚀 Considering this done!

**Comment by lid-rs** [comment]
@astrojuanlu Here is an update of the PyPI downloads for both Kedro and Kedro-viz: https://prod-useast-b.online.tableau.com/#/site/mckinseyusproduction/views/PyPIDownloadsKedroandViz/2025OKRsDashboard?:iid=3
