### ISSUE TITLE
Hacktoberfest 2024

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-devrel#149]
@ankatiyar is leading 🎃

- Blog post by @stichbury (to be included in monthly update, same as last year)
- Image and slackmoji by @stephkaiser 
- Board on GitHub Projects by @astrojuanlu

**Comment by stephkaiser** [comment]
Please find the Hacktoberfest 2024 blog promo image here to download - https://www.figma.com/design/qk6phA6mnULZjYbGQvqHks/Kedro-Master-2024?node-id=1016-66515&t=0DAgnX22TfV1fDje-4

![Kedro-Hacktoberfest 2024 promo -1600x900](https://github.com/user-attachments/assets/985d7287-72b6-4792-8a19-8cc6508ec5f2)

**Comment by astrojuanlu** [comment]
OMG I love this so very much. That bright green somehow fits the Kedro branding so nicely. Announcements go tomorrow, blog post later in the week.

**Comment by astrojuanlu** [comment]
https://github.com/kedro-org/kedro/issues/4203

**Comment by astrojuanlu** [comment]
Announced on LinkedIn, Bluesky, Mastodon. Next is the blog post and we'll be done.

**Comment by astrojuanlu** [comment]
This is ongoing!
