### ISSUE TITLE
ETL pipeline for kedro PyPI downloads: unreliable data source and alternatives

### ISSUE THREAD

**Issue by DimedS** [kedro-org/kedro-devrel#155]
We have set up an ETL pipeline to process Kedro PyPI downloads data and store it in our internal Snowflake space, as described in #145 . This pipeline operates as a GitHub Action, running the Kedro project daily in our internal repository: [kedro-pypi-to-snowflake](https://github.com/McK-Internal/kedro-pypi-to-snowflake).

### Challenges Faced

Approximately 1.5 months ago, an issue #154  arose when the data source changed. It became possible to query only one specific date per request, instead of reading the entire dataset. To address this, we modified the Kedro project to implement an incremental approach, allowing us to process data day-by-day effectively.

As of **2024-11-25**, the data source has started returning completely empty responses. This new problem renders our current data source unreliable.

### Proposed Solutions
1. **Investigate Current Data Source** - explore the reasons behind the empty responses to determine if the issue can be resolved.

2. **Switch to Raw PyPI Dataset in BigQuery**  as an alternative data source. Details can be found [here](https://github.com/kedro-org/kedro-devrel/issues/154#issuecomment-2428994160).

**Comment by DimedS** [comment]
For some reason, our data source [clickpy.clickhouse.com](https://clickpy.clickhouse.com/) stopped updating its views as of 2024-11-24. This issue is also visible on their dashboards.

<img width="1087" alt="Screenshot 2024-12-02 at 10 44 30" src="https://github.com/user-attachments/assets/b1d65ac9-9d8d-4310-b942-f8d5e8405e5c">


Currently, the only option seems to be switching to Raw BigQuery. What do you think, @astrojuanlu?

**Comment by astrojuanlu** [comment]
Thanks for the investigation @DimedS. Please open an issue in https://github.com/ClickHouse/clickpy/issues/, and in parallel I agree, let's finally switch to BigQuery.

**Comment by DimedS** [comment]
Issue created: https://github.com/ClickHouse/clickpy/issues/106

Will start work on moving to BigQuery

**Comment by DimedS** [comment]
# Moved PyPI Downloads ETL data source to a raw BigQuery table

1. Data is now transferred to two tables in our Snowflake storage:
   - `KEDRO_BI_DB.PYPI.AGGREGATED_DOWNLOADS`: Maintains the same format as before.
   - `KEDRO_BI_DB.PYPI.AGGREGATED_DOWNLOADS_EXT`: Includes additional aggregates such as country, operating system, CI flag, and cloud platform name (if provided).

2. To query BigQuery, I created a sandbox account on `platform.mckinsey`. I used my credentials to configure GHA secrets in our internal repository.

3. Updated the code in our internal repository: [https://github.com/McK-Internal/kedro-pypi-to-snowflake](https://github.com/McK-Internal/kedro-pypi-to-snowflake). Additionally, I set up GitHub Actions to fully reload both tables daily at 6 a.m.

@astrojuanlu , could you please review the dashboards and confirm that everything looks good?

**Comment by astrojuanlu** [comment]
From the looks of it, this is working now! Thanks @DimedS, closing
