### ISSUE TITLE
Create Kedro Academy materials about using VSCode

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#18]
This is a child task of https://github.com/kedro-org/kedro-devrel/issues/13 and covers creation of MVP slides about using VSCode for basics of development as part of the Kedro Academy course.

**Comment by astrojuanlu** [comment]
Do we want to tackle this for the next batch? As discussed in https://github.com/kedro-org/kedro-devrel/issues/35 I think Gitpod is the best option for doing the exercises, so we will be using a VS Code-based interface.

**Comment by astrojuanlu** [comment]
I created a basic version of the deck.
