### ISSUE TITLE
Setup Linen on Kedro Slack

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-devrel#28]
## Description

We already have [Linen active on the Kedro Discord. Linen makes it possible for us to access messages beyond the 6-month limit on Slack for improved collaboration and knowledge sharing. We activated Linen we sunset Discord. 

The scope of this ticket includes working with @datajoely to setup Linen on our Slack workspace.

**Comment by datajoely** [comment]
Big fan of linen for the purposes of SEO detectable mirror of the knowledge corpus which doesn't require users to sign up to get the right bit of knowledge.

In terms of actually exporting data, we could do this the old fashioned way and call the APIs directly
https://slack.com/intl/en-gb/help/articles/201658943-Export-your-workspace-data

**Comment by astrojuanlu** [comment]
I believe @yetudada has already adjusted the branding, this is how it looks like for visitors now:

![image](https://user-images.githubusercontent.com/316517/224995759-528b3c06-bff4-4313-a1b7-8c4151927186.png)

I'm not in the loop of what's the state of private channels though. Tried to enter the admin interface and couldn't see the ones I'm a member of.

**Comment by yetudada** [comment]
Yes, this ticket is complete! Let me close it.
