### ISSUE TITLE
Blog post about using Polars and Kedro

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#29]
Based on @astrojuanlu's upcoming talk:
“Analyze your data at the speed of light with Polars and Kedro”

Abstract: “The pandas library is one of the key factors that enabled the growth of Python in the Data Science industry and continues to help data scientists thrive almost 15 years after its creation. Because of this success, nowadays several open-source projects claim to improve pandas in various ways. Polars is one of those new dataframe libraries: it’s backed by Arrow and Rust, and offers an expressive API for dataframe manipulation with excellent performance. In this webinar I will show you how to combine Polars for your data manipulation needs with Kedro, a data science framework that will help you write more maintainable code.”

**Comment by astrojuanlu** [comment]
Been thinking a bit more about this. Even though I initially proposed the talk as a way to talk about Polars + Kedro, support for Polars in kedro-datasets is still experimental and a bit cumbersome, for a variety of reasons:

- one has to install a development version https://github.com/astrojuanlu/talk-kedro-polars/blob/e6a422bbbaa799049f4ee247cbdfd63eeefadcf8/requirements.txt#L17 
- there is no parquet reading capabilities yet, this PR stalled https://github.com/kedro-org/kedro-plugins/pull/170
- any non-trivial dataset will require using the `TemplatedConfigLoader` or subclassing `OmegaConfigLoader` until https://github.com/kedro-org/kedro/issues/2407 is in

I'm thinking what's the best way of framing this ahead of my talk, but whatever I write in the short term, we'll probably need to do another round of marketing and outreach once these issues have settled.

**Comment by astrojuanlu** [comment]
This is now almost done, will make it on time for publishing this week.
