### ISSUE TITLE
Convert Kedro principles documentation page into a blog post

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#32]
[The Kedro principles page](https://kedro.readthedocs.io/en/latest/faq/kedro_principles.html) is a nice enough page but doesn't really work in documentation. Let's move it out into a post or page.

Or, failing that, a topic page that sits on the website (but isn't in the nav, so you can find it organically but we don't push it to the user).

**Comment by stichbury** [comment]
@astrojuanlu Do you have any thoughts on this one? I was thinking about maybe moving the [principles page](https://kedro.readthedocs.io/en/latest/faq/kedro_principles.html) to make it a markdown piece of content in the Kedro project, rather than a page of documentation, and then later rewriting it as a blog post. Just trying to have a "spring clean" and remove some of the less useful pieces of content that lurk at the bottom of the table of contents.

**Comment by astrojuanlu** [comment]
@stichbury Similarly to gh-2368, what do you think of having these as dev docs? They function as "guiding principles" - I agree they're only anecdotically interesting for users, but much more for developers. And it doesn't harm turning them into a blog post as well. In either case, I agree with removing them from the user docs.

**Comment by stichbury** [comment]
Just as a matter of interest, the Principles page doesn't show up on Heap as having any large number of page views in a year (it's lower than any of those reported, so is getting less than 1700 views per year)

**Comment by stichbury** [comment]
This happened https://kedro.org/blog/development-principles-for-opinionated-teams
