### ISSUE TITLE
Archive content on the `kedro-training` repo and sunset it

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#39]
I've checked and nobody seems to be using the `kedro-training` repo content, which has dated, but may be useful later for future courses. Let's archive it for now and start adopting `kedro-academy` as the de facto location for publicly-shared decks and training graphics.

**Comment by astrojuanlu** [comment]
And noting that we could bring part of Antony's https://github.com/AntonyMilneQB/kedro-university

**Comment by astrojuanlu** [comment]
I'll do this and gh-35 at the same time.

**Comment by astrojuanlu** [comment]
Opened https://github.com/kedro-org/kedro-academy/pull/4 to move all the content from kedro-training to kedro-academy and https://github.com/kedro-org/kedro-training/pull/27 to add an archival note to kedro-training. I don't have permissions to admin kedro-training, so I can't change the GitHub description nor actually archive the repository.

**Comment by astrojuanlu** [comment]
All contents will be under kedro-academy after https://github.com/kedro-org/kedro-academy/pull/5 and https://github.com/kedro-org/kedro-academy/pull/6 are merged.

**Comment by astrojuanlu** [comment]
Done!
