### ISSUE TITLE
Consider how to use the `kedro-community` repo and clean up any broken links/add new content

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#40]
This is a general "housekeeping" ticket to work out how we use [`kedro-community`](https://github.com/kedro-org/kedro-community) better so it's up to date and useful.

**Comment by astrojuanlu** [comment]
I think we should repurpose that repo into an "awesome-kedro" (https://github.com/sindresorhus/awesome/blob/main/awesome.md) so it has a more community-friendly structure.

**Comment by astrojuanlu** [comment]
To note: https://github.com/fkromer/awesome-kedro exists

**Comment by astrojuanlu** [comment]
Sent a second ping over https://github.com/fkromer/awesome-kedro, awaiting for response.

**Comment by astrojuanlu** [comment]
awesome-kedro has been archived.

**Comment by astrojuanlu** [comment]
Let's try to do this in the next sprint.

**Comment by stichbury** [comment]
Sounds like a plan!

**Comment by astrojuanlu** [comment]
https://github.com/kedro-org/awesome-kedro

@kedro-org/kedro-admin could you please enable issues there?

And maybe even create a `Advocacy` team including @yetudada, @stichbury, and I with more permissions over

- kedro-devrel
- kedro-academy
- awesome-kedro
- kedro-community (only so that I can archive it)

(And while you're at it, could you change the YouTube link to https://www.youtube.com/@kedro-python in https://github.com/kedro-org?)

**Comment by astrojuanlu** [comment]
Thanks a lot @yetudada and sorry I dragged so long on this - taking over from here.

> I want to archive Kedro-Community for you but I think we should let people know on the README.md that we're doing this.

Yep, I'll make an edit to the README ahead of doing that.

> I also looked into creating teams with different access levels for different repos and it's not possible on our account because it's an enterprise feature.

Interesting - isn't this what https://github.com/orgs/kedro-org/teams/kedro-developers/repositories and https://github.com/orgs/kedro-org/teams/kedro-framework/repositories do for example?

**Comment by astrojuanlu** [comment]
Merged this repo with `awesome-kedro` at https://github.com/kedro-org/awesome-kedro/pull/1

**Comment by astrojuanlu** [comment]
Remaining tasks:

- [ ] Merge all the cross-linked PRs and wait for them to be deployed
- [ ] Unpin kedro-community from https://github.com/kedro-org/ and pin https://github.com/kedro-org/awesome-kedro instead
- [ ] Update README of this repo
- [ ] Archive this repo
