### ISSUE TITLE
Create a video walkthrough of Kedro-Viz

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-devrel#45]
### Context
This captures the creation of a video walkthrough to promote  and encourage awareness and adoption of Kedro-Viz. It is part of a wider.

### Goal
The goal is to  create a video walkthrough highlighting what Kedro-Viz is, what problem it solves, and solution (features).

These key features include:
- Dataset preview.
- Plotly and Matlplotlib plots.
- Experiment tracking.

Audience is both technical and non-technical people.

**Comment by NeroOkwa** [comment]
This has been completed, and would be uploaded to the Kedro youtube channel.

**Comment by astrojuanlu** [comment]
You might want to keep this open until the videos are online? To have a comprehensive "definition of done" 😄
