### ISSUE TITLE
"Hamilton vs Kedro" plus "Hamilton and Kedro"

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#48]
How the two compare. How the two complement each other. 

Based on some discussion following [this discussion on hacker news](https://news.ycombinator.com/item?id=35056903) and some ongoing discussion over on the Hamilton Slack

> We used Kedro at [MoovAI](https://moov.ai/en/). The standardized structure is reaaally valuable in consulting where team members change over the course of a project! The folks at [potloc](https://www.potloc.com/) like it a lot and presented it at the most recent Montréal MLOps community event!
> While using Kedro, I wanted to create modular functional code for data transformation, but creating a node for each function would require me to specify input-output for each node. In addition, if the output of these nodes would be pandas Series, I would have to assemble them manually at intermediary steps.
> That's when I learned about Hamilton, which exactly met my needs for quick iterations of data processing pipelines with little/no boilerplate. I ended up calling Hamilton within a single Kedro node! (similar to [Metaflow+Hamilton](https://outerbounds.com/blog/developing-scalable-feature-engineering-dags/))
> I think one of the main appeal of Kedro for orgs is the [visualization tool](https://github.com/kedro-org/kedro-viz) that encompasses functions, data, code, experiments, etc. (+MLFlow and Airflow plugins). Integrating Kedro-viz with other DAG tools could be very exciting for users to have full visibility of their ETL pipeline. For example, at the MLOps meetup, someone asked if it would be possible to plug their Airflow ETL (upstream of the data science Kedro project) into the tool!

**Comment by astrojuanlu** [comment]
Shall we close this in favor of #41?
