### ISSUE TITLE
Blog post to celebrate World Product Day May 24 2023

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#59]
[World Product Day](https://www.mindtheproduct.com/world-product-day/) is coming soon and it would be great to have a blog post to promote at that time, particularly since it's close to the anniversary of open-sourcing Kedro IIRC.

I have a few ideas but I'm sure there are more that @yetudada and @NeroOkwa could contribute. For example:

* Quick win: convert recent presentation about how to be a more technical product manager into a post
* Large: what's it like to take a product open-source in an organisation like McKinsey? What are the top tips?  
* Large frog: write up a case study of a product feature and how we took it from inception to completion? I'd love to see coverage of Telemetry, as this is a keyword we could rank for and a useful study on how to go about adding this kind of "intrusive" feature, but less ambitious could be to take experiment tracking (as we already have some useful material on this and it would be great for Nero to write up)

@astrojuanlu and I will discuss possible overlap with what the QB marketing team are doing.

**Comment by stichbury** [comment]
This needs to be ready by 18/05 and sent over to QB team for review.

**Comment by NeroOkwa** [comment]
@stichbury this sounds like a great idea. I like the quick win option as it is general enough for anyone interested in building products or product management.

**Comment by stichbury** [comment]
This is now in draft on the blog and ready to publish
