### ISSUE TITLE
YouTube settings may need adjustment to allow video play within the blog

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#65]
@astrojuanlu When you've a moment, please could you take a look to see if you can enable video play within the Kedro blog?

I've embedded the Databricks presentation from the update meeting in the [blog post I wrote about it](https://kedro.org/blog/how-do-data-scientists-combine-kedro-and-databricks), and I'm seeing this:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/5180475/233972362-d68072f1-5e30-4cad-978e-897f7c3e4548.png">

**Comment by astrojuanlu** [comment]
Sorry, I had disabled embedding - please try again! (Feel free to reopen if it doesn't work)

**Comment by stichbury** [comment]
Speediest issue resolution ever. Thanks @astrojuanlu 

I realise now that I could have probably used 1P and done that for myself -- sorry.

**Comment by astrojuanlu** [comment]
> I realise now that I could have probably used 1P and done that for myself -- sorry.

Not quite - we don't have an account for shared access yet, although I can offer an alternative. I'll follow up in private.
