### ISSUE TITLE
Consider issuing (verifiable?) certificates

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#66]
Discussed on Slack. How does a company get to offer certificates via LinkedIn for people to register on their profiles/

**Comment by astrojuanlu** [comment]
Another option would be to explore the possibility of issuing it through the LF https://training.linuxfoundation.org/certification-catalog/

**Comment by astrojuanlu** [comment]
This is not going to be a priority in the short term.

**Comment by astrojuanlu** [comment]
Closing for now.
