### ISSUE TITLE
Create a launch deck for Collaborative Experiment Tracking.

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-devrel#72]
### Context
This is part of a wider collaborative experiment tracking product launch strategy [#74 ](https://github.com/kedro-org/kedro-devrel/issues/74). 

It captures the creation of a short presentation focused on the new collaborative experiment tracking feature [#1295](https://github.com/kedro-org/kedro-viz/issues/1295) on Kedro-Viz. 

### Goal
The goal is to create awareness and adoption of this feature.

**Comment by tynandebold** [comment]
Closing in favor of #75
