### ISSUE TITLE
Create a launch blog post for Collaborative Experiment Tracking.

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-devrel#73]
### Context
This is part of a wider collaborative experiment tracking product launch strategy [#74 ](https://github.com/kedro-org/kedro-devrel/issues/74). 

It captures the creation of a blog post  introducing the new collaborative experiment tracking feature [#1295](https://github.com/kedro-org/kedro-viz/issues/1295) on Kedro-Viz, and the pain point it solves. 

### Goal
The goal is to write a blog post to increase awareness and adoption of this new feature. 
This blog post would cover:

1. What is collaborative experiment tracking?
2. Why it is important to users/Why we have developed it?
3. How to get started with collaborative experiment tracking (Technical guide).

**Comment by stichbury** [comment]
I have added @rashidakanchwala to this ticket as I believe she'll be reaching out to work with me on docs/blog post planning.

**Comment by stichbury** [comment]
Tynan left some comments on this PR before he left and they need to be addressed before the blog post is published. @NeroOkwa  please can you see the post on Box for these?

It will also need at least one screengrab and I wonder if it's best to wait until (a) we have a release out so docs are updated and (b) we have rebranding so we can use screengrabs in new branding.
