### ISSUE TITLE
Review website copy in rebranded preview

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#83]
A small (I hope) task to review the website copy on the newly branded website in case any small tweaks would be beneficial at the time we make a new release. I'll create a set of suggestions here for signoff.

**Comment by stichbury** [comment]
"Kedro is an open sourced Python framework for creating maintainable and modular data science code"

[According to Microsoft](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source), I think this should be 

"Kedro is an **open-source** Python framework for creating maintainable and modular data science code"

Note that we are dropping the 'd' and inserting a hyphen

**Comment by stichbury** [comment]
> **Machine Learning Engineering**
> Puts the "engineering" back into data science because it borrows concepts from software engineering and applies them to machine-learning code. It is the foundation for clean, data science code.


Can we make the first sentence a proper sentence?

> **Machine Learning Engineering**
> Kedro is the foundation for clean, data science code. It borrows concepts from software engineering and applies them to machine-learning projects. 

Can

**Comment by stichbury** [comment]
> **Integrations**
Apache Spark, Pandas, Dask, Matplotlib, Plotly, fsspec, Apache Airflow, Jupyter Notebook and Docker.

Should we add any of the following?

- [ ] Databricks
- [ ] Prefect
- [ ] Kubeflow
- [ ] MLFlow

**Comment by stichbury** [comment]
> FAQs
> 
> You can find the [Kedro community on Slack](https://slack.kedro.org/).
> 
> We also maintain a list of articles, podcasts, talks, and Kedro showcase projects in the [kedro-community](https://github.com/kedro-org/kedro-community) repository.

Change link 

> FAQs
> 
> You can find the [Kedro community on Slack](https://slack.kedro.org/).
> 
> We also maintain a list of articles, podcasts, talks, and Kedro showcase projects in the [awesome-kedro](https://github.com/kedro-org/awesome-kedro) repository.

**Comment by stichbury** [comment]
> Ready to start?
> You are ready to get going with the Kedro workflow. But first, head to our documentation to learn how to install Kedro and then get up to speed with concepts like nodes, pipelines, the data catalog in our introductory tutorial.

Replace the copy

> Ready to start?
> Visit the introductory tutorial to learn how to install Kedro and get up to speed with concepts like nodes, pipelines, and the data catalog.
>

**Comment by stichbury** [comment]
@yetudada @astrojuanlu A few copy suggestions to update the website ahead of re-launch. I can collate all comments and build one single list of changes for the team to make.

**Comment by yetudada** [comment]
I like the changes on this! I have two points:

 - This is a larger change but can we [pull some of the copy from the deck](https://mckinsey.box.com/v/kedro-technical-presentation) into this?
 - On integrations, I would add the checked ones and only ones that GetInData have provided with their plugin ecosystem. We can't put Prefect because we don't support Prefect 2.0.

**Comment by stichbury** [comment]
Closing this because I've created a final collated set of changes for the website here: https://github.com/kedro-org/kedro-website/issues/143
