### ISSUE TITLE
Edit branding guidelines

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-devrel#85]
## Description 

This ticket documents the work done to update V1 of the branding guidelines. Changes include:
- Updating copy from @stichbury's edits
- Updating images 
- Doing a final review
- And uploading it to: https://github.com/kedro-org/kedro-artwork/tree/main (in a folder called `branding_guidelines`)

**Comment by stichbury** [comment]
I spotted one typo in the PDF from end of March, and there are possibly a couple of comma tweaks. But I'm happy to let them go if you want to release the existing PDF. If you need me to go into figma and fix, please let me know and can you pass me the link so I can resolve?

**Comment by stichbury** [comment]
@Mackay031 I have updated the Figma file to fix a couple of minor typos, as mentioned above. It's good to go from my perspective.

**Comment by tynandebold** [comment]
Here it is: https://github.com/kedro-org/kedro-brand-identity/blob/main/Kedro_Brand_Guidelines.pdf
