### ISSUE TITLE
Graphic for blog post

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#89]
Hi @Mackay031 and @stephkaiser 

I'm writing a blog post about the history of Kedro to celebrate our anniversary. It would be awesome to have a custom graphic in it, and I wondered if we could have something that takes this plot logging the number of GitHub stars

https://star-history.com/#kedro-org/kedro

And adds labels for the various points in the timeline, like LF adoption, Website launch etc.

I am looking to go live the blog post sometime this week, all being well, so it's short notice and if necessary I could just use the visual that's downloadable from the site, and either annotate myself (or leave it as is). Wanted to see if it's possible to get your time on it but if your priorities are already set for the sprint, I don't think it's high enough to warrant adjusting them. Totally up to you.

**Comment by Mackay031** [comment]
HI Jo, I have a concept to show you tomorrow. Just to confirm, its 4 years right? :)

**Comment by stichbury** [comment]
@Mackay031 Yes it is, and you've now shown me the concept which is great. Closing this.
