### ISSUE TITLE
Create a list of useful tools and services that we need for devrel 

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-devrel#9]
Here's my list so far:

* [SEMRush](https://www.semrush.com/projects/)
* [Content King](https://www.contentkingapp.com/)
* [Surfer SEO](https://surferseo.com/)
* [Orbit](https://orbit.love/)
* [Mentimeter](https://mentimeter.com)

**Comment by astrojuanlu** [comment]
To start, I'd love to have something like Orbit yes. Been using it for the past ~year and it's very useful to connect Slack users, GitHub profiles, social media mentions, and other identity sources like LinkedIn. This would help identifying entities engaging with the Kedro community too.

**Comment by astrojuanlu** [comment]
Asked for permission to use Orbit and Luma.

**Comment by stichbury** [comment]
Closing this -- we have a list, if not the tools.
